### ISSUE TITLE
How do you do the GIF trick?

### ISSUE THREAD

**Issue by Nyameliaaaa** [CyrisXD/CyrisXD#1]

**Comment by CyrisXD** [comment]
I created an animated web page then recorded it with my Macbook and converted it into a GIF manually. You'll have to Google for the conversion tools but the layout is made with [particlejs](https://vincentgarreau.com/particles.js/) and [typewriterjs](https://github.com/tameemsafi/typewriterjs)

**Comment by SohilK03** [comment]
Can you pls share the code @CyrisXD
