### ISSUE TITLE
Bio GIF

### ISSUE THREAD

**Issue by VinayakBector2002** [CyrisXD/CyrisXD#3]
Hey Chris!
Firstly you have a really awesome readme!! I absolutely love it 🥇
https://github.com/CyrisXD/CyrisXD/blob/master/bio.gif
I wanna make a gif like this as well and seek you advise on the same.
Thanks in advance
Best Regards
Bector

**Comment by chrishough** [comment]
I am trying to find where that was created too.

**Comment by CyrisXD** [comment]
I built this as a webpage and then recorded it with a screen recorder -> GIF 

The particles are: https://vincentgarreau.com/particles.js/
The typewriter effect is with: https://safi.me.uk/typewriterjs/

Hope this helps.

**Comment by chrishough** [comment]
Thank you
